# -*- coding: utf-8 -*-
"""Diskominfo-Public-Information-Satisfaction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHkrJapzwfDGXCS_50IUVxk6GpI8Ieiw

### Penjelasan Cell: Konsolidasi Library Import

Cell ini berfungsi untuk mengkonsolidasikan semua pernyataan `import` dari berbagai *library* Python yang dibutuhkan di seluruh *notebook*. Tujuannya adalah untuk meningkatkan keterbacaan, memudahkan manajemen dependensi, dan memastikan *library* diimpor secara efisien di satu tempat.
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.ensemble import RandomForestClassifier
import shap
import numpy as np
import matplotlib.patches as mpatches
from matplotlib.patches import FancyArrowPatch
import scipy.stats as stats
from IPython.display import display

#=====LOAD & RENAME=====#

df = pd.read_csv('Data-Responden (1).csv',
                 sep=';',
                 on_bad_lines='skip')

#Renable Colume Supaya Rapi
df.columns = ['Nama', 'Pendidikan', 'Pekerjaan', 'Kontak', 'Waktu',
              'Index', 'Usia', 'Jenis_Kelamin',
              'Q1','Q2','Q3','Q4','Q5','Q6','Q7',
              'Q8','Q9','Q10','Q11','Q12','Q13','Q14','Q15']

print(df.shape)
print(df.head(3))

"""### Penjelasan Cell: Pemuatan dan Penamaan Ulang Data

Cell ini bertujuan untuk memuat dataset responden dari Google Drive ke dalam DataFrame. Setelah dimuat, nama-nama kolom disesuaikan agar lebih deskriptif dan mudah dipahami untuk analisis selanjutnya. Pada akhirnya, cell ini juga menampilkan dimensi data dan beberapa baris pertama untuk pratinjau cepat.
"""

#===== CLEANING & DROP =====#

# Kolom yang tidak relevan sama sekali
drop_cols = ['Nama', 'Kontak', 'Waktu']
df = df.drop(columns=drop_cols)

# Pisahkan fitur clustering dan demografi
q_cols = ['Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9','Q10','Q11','Q12','Q13','Q14','Q15']
demo_cols = ['Pendidikan', 'Pekerjaan', 'Usia', 'Jenis_Kelamin', 'Index']

X = df[q_cols]        # Ini yang masuk clustering
demo = df[demo_cols]  # Ini untuk interpretasi nanti

print("Shape X (fitur clustering):", X.shape)
print("Shape demo:", demo.shape)
print()
print(X.head(3))

"""### Penjelasan Cell: Pembersihan dan Pemisahan Data

Cell ini melakukan pra-pemrosesan data dengan menghapus kolom yang tidak relevan, kemudian memisahkan fitur untuk klustering (`X`) dari data demografi (`demo`). Ini penting untuk memastikan data siap digunakan dalam analisis klustering dan untuk interpretasi hasil demografi selanjutnya.
"""

#===== Normalisasi menggunakan Standard Scaling (Z-score) =====#


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Sebelum scaling - mean Q1:", X['Q1'].mean().round(2))
print("Sesudah scaling - mean Q1:", X_scaled[:, 0].mean().round(2))
print("Sesudah scaling - std Q1 :", X_scaled[:, 0].std().round(2))

"""### Penjelasan Cell: Normalisasi Data (Standard Scaling)

Cell ini menerapkan teknik Standard Scaling (Z-score normalisasi) pada fitur klustering (`X`) menggunakan `StandardScaler`. Normalisasi ini krusial agar algoritma K-Means dapat bekerja secara efektif, karena K-Means sensitif terhadap skala fitur. Verifikasi scaling juga disertakan untuk memastikan data telah diskalakan dengan benar.
"""

#===== EDA (Exploratory Data Analysis) =====#


# Rata-rata skor tiap pertanyaan
q_means = X.mean().sort_values()

plt.figure(figsize=(10, 6))
bars = plt.barh(q_means.index, q_means.values, color='steelblue', edgecolor='white')
plt.axvline(X.mean().mean(), color='red', linestyle='--', label=f'Rata-rata keseluruhan: {X.mean().mean():.1f}')
plt.title('Rata-rata Skor per Pertanyaan (Q1–Q15)', fontsize=13, fontweight='bold')
plt.xlabel('Rata-rata Skor')
plt.legend()
plt.tight_layout()
plt.show()

"""### Penjelasan Cell: Analisis Data Eksplorasi (EDA) - Rata-rata Skor per Pertanyaan

Cell ini melakukan analisis data eksplorasi untuk memahami distribusi skor rata-rata pada setiap pertanyaan (Q1-Q15). Visualisasi menggunakan *bar chart* horizontal ini membantu mengidentifikasi pertanyaan mana yang memiliki skor kepuasan tinggi dan rendah, serta rata-rata keseluruhan sebagai referensi.
"""

#===== Clustering K-Means =====#


inertias = []
sil_scores = []
K_range = range(2, 9)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)
    sil_scores.append(silhouette_score(X_scaled, km.labels_))

print("K | Inertia | Silhouette")
for k, inertia, sil in zip(K_range, inertias, sil_scores):
    print(f"{k} | {inertia:.2f}  | {sil:.3f}")

"""### Penjelasan Cell: Klustering K-Means - Penentuan Jumlah Cluster Optimal

Cell ini bertujuan untuk menentukan jumlah cluster (K) yang paling optimal untuk algoritma K-Means. Proses ini melibatkan iterasi K-Means dengan berbagai jumlah cluster (`K_range`) dan evaluasi hasilnya menggunakan metrik *Inertia* (metode Elbow) dan *Silhouette Score*. Hasil berupa tabel `K`, `Inertia`, dan `Silhouette Score` disajikan untuk membantu dalam penentuan K optimal.
"""

#===== visualisasikan =====#

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Elbow
ax1.plot(K_range, inertias, 'o-', color='steelblue', linewidth=2, markersize=7)
ax1.axvline(x=3, color='red', linestyle='--', label='K optimal = 3')
ax1.set_title('Elbow Method', fontweight='bold')
ax1.set_xlabel('Jumlah Cluster (K)')
ax1.set_ylabel('Inertia')
ax1.legend()

# Silhouette
ax2.plot(K_range, sil_scores, 's-', color='green', linewidth=2, markersize=7)
ax2.axvline(x=3, color='red', linestyle='--', label='K optimal = 3')
ax2.set_title('Silhouette Score', fontweight='bold')
ax2.set_xlabel('Jumlah Cluster (K)')
ax2.set_ylabel('Silhouette Score')
ax2.legend()

plt.tight_layout()
plt.show()

"""### Penjelasan Cell: Visualisasi Metode Elbow dan Silhouette Score

Cell ini memvisualisasikan hasil dari evaluasi klustering K-Means menggunakan metode Elbow dan Silhouette Score. Plot `Inertia` dan `Silhouette Score` ditampilkan untuk berbagai nilai K, dengan indikasi `K=3` sebagai jumlah cluster optimal. `K=3` dipilih berdasarkan titik 'siku' yang jelas pada metode Elbow dan nilai *Silhouette Score* yang relatif tinggi, menunjukkan struktur cluster yang baik.
"""

#===== Final Clustering dengan K=3 =====#

km_final = KMeans(n_clusters=3, random_state=42, n_init=10)
df['Cluster'] = km_final.fit_predict(X_scaled)

print(df['Cluster'].value_counts())

"""### Penjelasan Cell: Klustering Final dengan K=3

Cell ini menerapkan algoritma K-Means dengan jumlah cluster final `K=3` pada data yang telah diskalakan (`X_scaled`). Hasil klustering, yaitu label cluster untuk setiap responden, kemudian ditambahkan sebagai kolom baru (`Cluster`) pada DataFrame asli (`df`). Distribusi jumlah responden di setiap cluster juga ditampilkan untuk memberikan gambaran ukuran masing-masing segmen.
"""

#===== Interpretasi Cluster =====#

# Gabungkan cluster dengan demografi
cluster_profile = df.groupby('Cluster')[['Index'] + q_cols].mean().round(2)
print(cluster_profile)

"""### Penjelasan Cell: Interpretasi Profil Cluster

Cell ini bertujuan untuk menginterpretasikan karakteristik setiap cluster yang terbentuk. Ini dilakukan dengan menghitung rata-rata skor dari `Index` kepuasan dan semua pertanyaan `Q1` hingga `Q15` untuk setiap cluster. Hasilnya, `cluster_profile`, memberikan gambaran jelas tentang profil unik masing-masing segmen masyarakat.
"""

#===== visualisasikan profil ketiga cluster =====#

cluster_names = {0: 'Puas Merata', 1: 'Puas Tidak Merata', 2: 'Kurang Puas'}
colors = {0: 'steelblue', 1: 'orange', 2: 'tomato'}

plt.figure(figsize=(14, 6))
for cluster in [0, 1, 2]:
    data = cluster_profile.loc[cluster, q_cols]
    plt.plot(q_cols, data, marker='o', linewidth=2,
             label=cluster_names[cluster], color=colors[cluster])

plt.title('Profil Rata-rata Jawaban per Cluster', fontweight='bold', fontsize=13)
plt.xlabel('Pertanyaan')
plt.ylabel('Rata-rata Skor')
plt.ylim(50, 100)
plt.legend()
plt.tight_layout()
plt.show()

"""### Penjelasan Cell: Visualisasi Profil Rata-rata Jawaban per Cluster

Cell ini memvisualisasikan `cluster_profile` dalam bentuk *line plot* untuk membandingkan rata-rata skor jawaban pada setiap pertanyaan (Q1-Q15) di antara ketiga cluster. Visualisasi ini membantu menyoroti kekuatan dan kelemahan relatif dari masing-masing segmen masyarakat terhadap berbagai aspek pengelolaan informasi.
"""

#===== Demografi di tiap cluster =====#

for cluster in [0, 1, 2]:
    sub = df[df['Cluster'] == cluster]
    print(f"\n{'='*40}")
    print(f"Cluster {cluster} — {cluster_names[cluster]} (n={len(sub)})")
    print(f"Index rata-rata : {sub['Index'].mean():.2f}")
    print(f"Pekerjaan dominan : {sub['Pekerjaan'].value_counts().index[0]}")
    print(f"Pendidikan dominan: {sub['Pendidikan'].value_counts().index[0]}")
    print(f"Usia rata-rata  : {sub['Usia'].mean():.1f} tahun")
    print(f"Gender dominan  : {sub['Jenis_Kelamin'].value_counts().index[0]}")

"""### Penjelasan Cell: Analisis Demografi per Cluster

Cell ini menyajikan ringkasan demografi untuk setiap cluster, termasuk jumlah responden, rata-rata `Index` kepuasan, serta pekerjaan, pendidikan, usia, dan jenis kelamin yang dominan. Analisis ini membantu memahami profil demografi unik dari masing-masing segmen masyarakat.
"""

#===== Validasi statistik =====#


print("Uji Kruskal-Wallis — Perbedaan Index antar Cluster\n")
groups = [df[df['Cluster'] == c]['Index'].values for c in [0, 1, 2]]
stat, p = stats.kruskal(*groups)
print(f"Statistik : {stat:.3f}")
print(f"P-value   : {p:.6f}")

if p < 0.05:
    print("\n✅ Ketiga cluster berbeda secara signifikan (p < 0.05)")
else:
    print("\n❌ Tidak ada perbedaan signifikan antar cluster")

"""### Penjelasan Cell: Validasi Statistik - Uji Kruskal-Wallis

Cell ini melakukan Uji Kruskal-Wallis untuk memvalidasi apakah ada perbedaan signifikan dalam `Index` kepuasan antara ketiga cluster. Uji ini penting untuk secara statistik mengkonfirmasi keberhasilan proses klustering dalam memisahkan segmen-segmen dengan tingkat kepuasan yang berbeda.
"""

#===== Random Forest - Improved =====#

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import classification_report, f1_score
import numpy as np

X_shap = df[q_cols]
y_shap = df['Cluster']

# Improved model — address class imbalance & overfitting
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=42
)
rf.fit(X_shap, y_shap)

# Classification report
print("=== Classification Report ===")
print(classification_report(y_shap, rf.predict(X_shap),
      target_names=['Puas Merata', 'Puas Tidak Merata', 'Kurang Puas']))

# K-Fold Cross Validation
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_results = cross_validate(rf, X_shap, y_shap, cv=skf,
                            scoring=['f1_macro', 'accuracy'])

print("=== Cross Validation (5-Fold) ===")
print(f"Accuracy  : {cv_results['test_accuracy'].mean():.3f} ± {cv_results['test_accuracy'].std():.3f}")
print(f"Macro F1  : {cv_results['test_f1_macro'].mean():.3f} ± {cv_results['test_f1_macro'].std():.3f}")

"""### Penjelasan Cell: Persiapan SHAP - Pelatihan Model Random Forest

Cell ini melatih model *Random Forest Classifier* (`rf`) menggunakan fitur pertanyaan (Q1-Q15) untuk memprediksi label cluster. Model ini berfungsi sebagai dasar untuk analisis SHAP, yang akan digunakan untuk menginterpretasikan kontribusi setiap fitur terhadap penentuan cluster. Akurasi model yang tinggi (1.0) menunjukkan kemampuan prediktif yang kuat, ideal untuk interpretasi SHAP.
"""

#===== SHAP - Explainability : tahap kalkulasi SHAP =====#

explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_shap)

print("Jumlah cluster:", len(shap_values))
print("Shape per cluster:", shap_values[0].shape)

"""### Penjelasan Cell: Kalkulasi SHAP Values

Cell ini menghitung nilai SHAP (`shap_values`) menggunakan `shap.TreeExplainer` pada model *Random Forest* yang telah dilatih. SHAP values ini mengukur kontribusi setiap fitur pertanyaan (Q1-Q15) terhadap prediksi cluster untuk setiap responden. Hasil perhitungan ini akan digunakan untuk visualisasi *feature importance*.
"""

#===== SHAP Summary Plot - Polish Version =====#


# Label lengkap
q_labels_short = {
    'Q1' : 'Q1  — Akses via Media Massa',
    'Q2' : 'Q2  — Ingat Info 3 Bulan',
    'Q3' : 'Q3  — Bisa Sebutkan Info',
    'Q4' : 'Q4  — Bisa Jelaskan Info',
    'Q5' : 'Q5  — Info Akurat & Bebas Kesalahan',
    'Q6' : 'Q6  — Info Mudah Dipahami',
    'Q7' : 'Q7  — Info Mudah Diperoleh',
    'Q8' : 'Q8  — Info Tersedia saat Dibutuhkan',
    'Q9' : 'Q9  — Info Sesuai Kebutuhan',
    'Q10': 'Q10 — Akses Info Mudah Digunakan',
    'Q11': 'Q11 — Info Sesuai Kebutuhan Saya',
    'Q12': 'Q12 — Bisa Bedakan Info Resmi',
    'Q13': 'Q13 — Info Ada di Media Pemprov',
    'Q14': 'Q14 — Info Bermanfaat Selesaikan Masalah',
    'Q15': 'Q15 — Pemprov Libatkan Masyarakat',
}

shap_array = np.array(shap_values)
mean_shap = np.abs(shap_array).mean(axis=(0, 2))

shap_df = pd.DataFrame({
    'fitur'     : q_cols,
    'label'     : [q_labels_short[q] for q in q_cols],
    'importance': mean_shap
}).sort_values('importance')

# Warna berdasarkan kuartil
q75 = shap_df['importance'].quantile(0.75)
q50 = shap_df['importance'].median()

colors = ['#E76F51' if v >= q75 else
          '#F4A261' if v >= q50 else
          '#52B788' for v in shap_df['importance']]

fig, ax = plt.subplots(figsize=(12, 8))
fig.patch.set_facecolor('white')

bars = ax.barh(shap_df['label'], shap_df['importance'],
               color=colors, edgecolor='white', height=0.65)

# Nilai di ujung bar
for bar, val in zip(bars, shap_df['importance']):
    ax.text(val + 0.001, bar.get_y() + bar.get_height()/2,
            f'{val:.4f}', va='center', fontsize=8.5, color='#333333')

# Garis rata-rata
avg = mean_shap.mean()
ax.axvline(avg, color='#333333', linestyle='--',
           linewidth=1.2, label=f'Rata-rata: {avg:.4f}')

# Legend warna
p1 = mpatches.Patch(color='#E76F51', label='Sangat Dominan (Top 25%)')
p2 = mpatches.Patch(color='#F4A261', label='Cukup Dominan (25–50%)')
p3 = mpatches.Patch(color='#52B788', label='Kurang Dominan (Bawah 50%)')
ax.legend(handles=[p1, p2, p3], fontsize=9,
          loc='lower right', framealpha=0.9)

ax.set_title('SHAP Feature Importance\nFaktor Dominan Kepuasan Masyarakat terhadap Pengelolaan Informasi Publik',
             fontsize=13, fontweight='bold', pad=15)
ax.set_xlabel('Mean |SHAP Value|', fontsize=10)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.tick_params(axis='y', labelsize=9)

plt.tight_layout()
plt.show()

"""### Penjelasan Cell: SHAP Summary Plot - Overall Feature Importance

Cell ini memvisualisasikan *overall feature importance* menggunakan rata-rata absolut SHAP values untuk setiap pertanyaan (Q1-Q15). *Bar chart* horizontal ini menampilkan faktor-faktor dominan yang paling mempengaruhi kepuasan masyarakat secara keseluruhan, membantu mengidentifikasi aspek-aspek paling krusial dalam pengelolaan informasi publik.
"""

#===== SHAP - Per Cluster Polish Version =====#

fig, axes = plt.subplots(1, 3, figsize=(20, 7))
fig.suptitle('SHAP Feature Importance per Segmen Masyarakat\nFaktor Dominan Kepuasan pada Tiap Cluster',
             fontsize=13, fontweight='bold', y=1.02)

cluster_names = {0: 'Puas Merata', 1: 'Puas Tidak Merata', 2: 'Kurang Puas'}
cluster_colors = {0: '#2D6A4F', 1: '#E09F3E', 2: '#C1440E'}

for i, cluster in enumerate([0, 1, 2]):
    mean_shap_c = np.abs(shap_array[:, :, cluster]).mean(axis=0)

    shap_c = pd.DataFrame({
        'label'     : [q_labels_short[q] for q in q_cols],
        'importance': mean_shap_c
    }).sort_values('importance')

    q75_c = shap_c['importance'].quantile(0.75)
    base_color = cluster_colors[cluster]

    colors_c = [base_color if v >= q75_c else
                '#A8C5A0' if cluster == 0 else
                '#F4D03F' if cluster == 1 else
                '#E8A090'
                for v in shap_c['importance']]

    bars = axes[i].barh(shap_c['label'], shap_c['importance'],
                        color=colors_c, edgecolor='white', height=0.65)

    for bar, val in zip(bars, shap_c['importance']):
        axes[i].text(val + 0.0005, bar.get_y() + bar.get_height()/2,
                     f'{val:.4f}', va='center', fontsize=7.5)

    axes[i].set_title(f"Cluster {cluster} — {cluster_names[cluster]}\n(n={len(df[df['Cluster']==cluster])})",
                      fontweight='bold', fontsize=11)
    axes[i].set_xlabel('Mean |SHAP Value|', fontsize=9)
    axes[i].spines['top'].set_visible(False)
    axes[i].spines['right'].set_visible(False)
    axes[i].tick_params(axis='y', labelsize=8)

plt.tight_layout()
plt.show()

"""### Penjelasan Cell: SHAP Feature Importance per Cluster

Cell ini menyajikan visualisasi *SHAP feature importance* yang lebih rinci untuk setiap cluster secara terpisah. *Bar chart* horizontal ini menunjukkan faktor-faktor dominan yang berbeda yang mempengaruhi kepuasan dalam masing-masing segmen masyarakat. Visualisasi ini krusial untuk merumuskan rekomendasi strategis yang disesuaikan untuk setiap kelompok responden.
"""

#===== PRIORITY MATRIX (QUADRANT ANALYSIS) =====#
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap

# 1. Pastikan model rf dan data X_shap tersedia, lalu hitung SHAP values jika belum ada
try:
    explainer = shap.TreeExplainer(rf)
    shap_values = explainer.shap_values(X_shap)

    shap_array = np.array(shap_values)
    mean_shap = np.abs(shap_array).mean(axis=(0, 2))

    # Memastikan shap_df memiliki kolom 'label' untuk kebutuhan cell visualisasi summary
    shap_df = pd.DataFrame({
        'fitur'     : q_cols,
        'label'     : [q_labels_short[q] for q in q_cols],
        'importance': mean_shap
    })

    # 2. Persiapkan data: Gabungkan SHAP (Impact) dan Rata-rata Skor (Performance)
    impact = shap_df.set_index('fitur')['importance']
    performance = X.mean()

    matrix_df = pd.DataFrame({
        'Impact': impact,
        'Performance': performance
    })

    # 3. Tentukan threshold (garis tengah kuadran) menggunakan median
    med_impact = matrix_df['Impact'].median()
    med_perf = matrix_df['Performance'].median()

    plt.figure(figsize=(12, 10))
    sns.set_style("whitegrid")

    # Scatter plot
    scatter = sns.scatterplot(data=matrix_df, x='Performance', y='Impact', s=200, color='darkblue', alpha=0.6)

    # Tambahkan label pada setiap titik
    for i, txt in enumerate(matrix_df.index):
        plt.text(matrix_df.Performance.iloc[i]+0.2, matrix_df.Impact.iloc[i]+0.0005,
                 txt, fontsize=10, fontweight='bold')

    # Garis Kuadran
    plt.axvline(med_perf, color='red', linestyle='--', alpha=0.5)
    plt.axhline(med_impact, color='red', linestyle='--', alpha=0.5)

    # Label Kuadran
    plt.text(med_perf-5, med_impact+0.015, 'PRIORITAS UTAMA\n(High Impact, Low Score)', color='red', fontsize=12, fontweight='bold', ha='center')
    plt.text(med_perf+5, med_impact+0.015, 'PERTAHANKAN\n(High Impact, High Score)', color='green', fontsize=12, fontweight='bold', ha='center')
    plt.text(med_perf-5, med_impact-0.015, 'MONITOR\n(Low Impact, Low Score)', color='orange', fontsize=12, fontweight='bold', ha='center')
    plt.text(med_perf+5, med_impact-0.015, 'EFISIENSI\n(Low Impact, High Score)', color='blue', fontsize=12, fontweight='bold', ha='center')

    plt.title('Priority Matrix: Strategi Peningkatan Layanan Informasi Publik\nDiskominfo Prov. Kalbar', fontsize=15, fontweight='bold', pad=20)
    plt.xlabel('Performance (Rata-rata Skor)', fontsize=12)
    plt.ylabel('Impact (Mean |SHAP Value|)', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()
except NameError as e:
    print(f"Error: {e}. Pastikan cell pelatihan model Random Forest (rf) dan data (X_shap) sudah dijalankan.")

"""### Penjelasan Cell: Priority Matrix (Quadrant Analysis)

Cell ini mengubah hasil teknis SHAP menjadi alat pengambilan keputusan strategis. Dengan membagi pertanyaan ke dalam empat kuadran, Diskominfo dapat menentukan alokasi sumber daya secara efektif:

1.  **Prioritas Utama (Kiri Atas)**: Fitur yang sangat mempengaruhi kepuasan tetapi memiliki skor rendah. Ini adalah area yang harus segera diperbaiki.
2.  **Pertahankan (Kanan Atas)**: Fitur yang berpengaruh besar dan sudah memiliki skor tinggi. Merupakan aset utama layanan.
3.  **Monitor (Kiri Bawah)**: Fitur dengan skor rendah namun pengaruhnya tidak terlalu besar terhadap segmentasi saat ini.
4.  **Efisiensi (Kanan Bawah)**: Fitur dengan skor tinggi tetapi dampak terhadap segmentasi rendah. Tetap dijaga namun tidak memerlukan penambahan sumber daya masif.
"""

#===== Visualisasi Final - Summary =====#

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Ringkasan Hasil Analisis\nSegmentasi Kepuasan Masyarakat terhadap Pengelolaan Informasi Publik\nDiskominfo Provinsi Kalimantan Barat',
             fontsize=12, fontweight='bold', y=1.02)

# Kiri — Distribusi cluster
cluster_counts = df['Cluster'].value_counts().sort_index()
cluster_labels = ['Puas Merata\n(Cluster 0)',
                  'Puas Tidak Merata\n(Cluster 1)',
                  'Kurang Puas\n(Cluster 2)']
cluster_colors = ['#2D6A4F', '#F4A261', '#E76F51']

wedges, texts, autotexts = axes[0].pie(
    cluster_counts.values,
    labels=cluster_labels,
    autopct='%1.1f%%',
    colors=cluster_colors,
    startangle=90,
    pctdistance=0.75
)
for at in autotexts:
    at.set_fontsize(10)
    at.set_fontweight('bold')
axes[0].set_title('Distribusi Segmen Masyarakat\n(n=477)', fontweight='bold')

# Kanan — Top 5 faktor dominan keseluruhan
top5 = shap_df.tail(5)
bar_colors = ['#E76F51','#E76F51','#F4A261','#F4A261','#F4A261']
axes[1].barh(top5['label'], top5['importance'],
             color=bar_colors, edgecolor='white')
axes[1].set_title('Top 5 Faktor Dominan\n(SHAP Feature Importance)', fontweight='bold')
axes[1].set_xlabel('Mean |SHAP Value|')
for i, (val, label) in enumerate(zip(top5['importance'], top5['label'])):
    axes[1].text(val + 0.001, i, f'{val:.3f}', va='center', fontsize=9)

plt.tight_layout()
plt.show()

"""## Operasionalisasi Model: Surrogate Classifier untuk Klasifikasi Real-Time

Bagian ini mengimplementasikan model *Random Forest* sebagai sistem inferensi prediktif. Dengan model ini, Diskominfo dapat mengklasifikasikan data responden baru secara instan tanpa perlu menjalankan ulang seluruh proses klustering K-Means.
"""

#===== Sistem Inferensi Prediktif Real-Time =====#

def prediksi_segmen_baru(skor_jawaban):
    """
    Fungsi untuk memprediksi cluster responden baru.
    Input: List berisi 15 nilai (Q1-Q15)
    """
    # Konversi input ke DataFrame agar sesuai format training
    new_data = pd.DataFrame([skor_jawaban], columns=q_cols)

    # Prediksi Label & Probabilitas
    label_idx = rf.predict(new_data)[0]
    probs = rf.predict_proba(new_data)[0]

    # Mapping Nama Cluster
    cluster_map = {0: 'Puas Merata', 1: 'Puas Tidak Merata', 2: 'Kurang Puas'}
    nama_cluster = cluster_map[label_idx]

    print(f"--- HASIL KLASIFIKASI REAL-TIME ---")
    print(f"Prediksi Segmen : {nama_cluster}")
    print(f"Keyakinan Model : {probs[label_idx]*100:.2f}%")
    print(f"----------------------------------")

    return nama_cluster

# --- DEMO PENGGUNAAN ---
# Simulasi data responden baru yang masuk ke sistem
# Misal: Responden memberikan skor rendah di semua pertanyaan
contoh_responden_baru = [60, 50, 60, 40, 50, 60, 50, 40, 50, 40, 60, 50, 40, 50, 40]

# Jalankan Prediksi
hasil = prediksi_segmen_baru(contoh_responden_baru)

"""### Penjelasan Cell: Surrogate Classifier System

Model ini berfungsi sebagai 'jembatan' operasional. Keuntungannya:
1. **Efisiensi**: Tidak perlu melakukan akumulasi data batch untuk mengetahui posisi segmen responden.
2. **Skalabilitas**: Dapat diintegrasikan ke dalam dashboard monitoring real-time SIKEDIP.
3. **Aksi Cepat**: Jika sistem mendeteksi aliran responden baru terus menerus masuk ke Cluster 2 (Kurang Puas), tim Diskominfo dapat segera melakukan investigasi pada layanan terkait.

### Sistem Pengolahan Data Ekspor (Batch Processing)

Jika integrasi API belum tersedia, gunakan cell di bawah ini untuk memproses file hasil ekspor manual dari sistem SIKEDIP. Sistem akan otomatis memberikan label cluster pada setiap baris data baru menggunakan model *Surrogate Classifier* yang sudah dilatih.
"""

def proses_data_ekspor(file_path_baru):
    """
    Fungsi untuk memproses file CSV hasil ekspor manual dan memberikan label cluster.
    """
    try:
        # 1. Load data baru
        df_baru = pd.read_csv(file_path_baru, sep=';', on_bad_lines='skip')

        # 2. Penamaan kolom (asumsi format sama dengan data awal)
        # Sesuaikan jika format ekspor sedikit berbeda
        if len(df_baru.columns) == 23:
            df_baru.columns = ['Nama', 'Pendidikan', 'Pekerjaan', 'Kontak', 'Waktu',
                              'Index', 'Usia', 'Jenis_Kelamin',
                              'Q1','Q2','Q3','Q4','Q5','Q6','Q7',
                              'Q8','Q9','Q10','Q11','Q12','Q13','Q14','Q15']

        # 3. Prediksi menggunakan model Random Forest (rf)
        X_new = df_baru[q_cols]
        df_baru['Prediksi_Cluster'] = rf.predict(X_new)

        # 4. Mapping Nama Cluster
        cluster_map = {0: 'Puas Merata', 1: 'Puas Tidak Merata', 2: 'Kurang Puas'}
        df_baru['Nama_Segmen'] = df_baru['Prediksi_Cluster'].map(cluster_map)

        print(f"✅ Berhasil memproses {len(df_baru)} data responden baru.")
        display(df_baru[['Nama', 'Nama_Segmen', 'Index']].head())

        return df_baru
    except Exception as e:
        print(f"❌ Gagal memproses file: {e}")

# --- CARA PAKAI ---
# Ganti path di bawah ini dengan lokasi file ekspor terbaru Anda
# hasil_batch = proses_data_ekspor('/content/drive/MyDrive/Projects/Skripsi/Data-Responden-Update.csv')"

"""### Penjelasan Cell: Ringkasan Hasil Analisis - Distribusi Cluster & Top 5 Faktor Dominan

Cell ini menyajikan ringkasan eksekutif dari hasil analisis. Ini mencakup dua visualisasi utama: *pie chart* yang menunjukkan distribusi responden di antara cluster, dan *bar chart* yang menampilkan Top 5 faktor dominan secara keseluruhan berdasarkan SHAP *feature importance*. Ringkasan ini sangat berguna untuk presentasi dan pemahaman cepat.
"""

#===== Heatmap Korelasi Q1-Q15 =====#

plt.figure(figsize=(12, 9))

corr = X[q_cols].corr()

mask = np.triu(np.ones_like(corr, dtype=bool))

sns.heatmap(
    corr,
    mask=mask,
    annot=True,
    fmt='.2f',
    cmap='RdYlGn',
    center=0,
    vmin=-1, vmax=1,
    linewidths=0.5,
    annot_kws={'size': 8},
    square=True
)

plt.title('Matriks Korelasi Antar Dimensi Pengelolaan Informasi Publik\n(Q1 – Q15)',
          fontsize=13, fontweight='bold', pad=15)
plt.xticks(fontsize=9)
plt.yticks(fontsize=9, rotation=0)
plt.tight_layout()
plt.show()

"""### Penjelasan Cell: Heatmap Korelasi Antar Dimensi Pengelolaan Informasi Publik

Cell ini memvisualisasikan hubungan korelasi antar pertanyaan survei (Q1-Q15) menggunakan *heatmap*. Visualisasi ini membantu memahami bagaimana setiap pertanyaan terkait satu sama lain, mengidentifikasi kelompok pertanyaan yang mengukur dimensi serupa, dan menunjukkan kekuatan serta arah korelasi.
"""

#===== Distribusi Index per Cluster =====#

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle('Distribusi Index Kepuasan per Segmen Masyarakat',
             fontsize=13, fontweight='bold', y=1.02)

cluster_names = {0: 'Puas Merata', 1: 'Puas Tidak Merata', 2: 'Kurang Puas'}
cluster_colors = {0: '#2D6A4F', 1: '#F4A261', 2: '#E76F51'}

for i, cluster in enumerate([0, 1, 2]):
    sub = df[df['Cluster'] == cluster]['Index']

    axes[i].hist(sub, bins=15, color=cluster_colors[cluster],
                 edgecolor='white', alpha=0.85)
    axes[i].axvline(sub.mean(), color='black', linewidth=2,
                    linestyle='--', label=f'Mean: {sub.mean():.1f}')
    axes[i].axvline(sub.median(), color='gray', linewidth=1.5,
                    linestyle=':', label=f'Median: {sub.median():.1f}')
    axes[i].set_title(f"Cluster {cluster} — {cluster_names[cluster]}\n(n={len(sub)})",
                      fontweight='bold')
    axes[i].set_xlabel('Index Kepuasan')
    axes[i].set_ylabel('Jumlah Responden')
    axes[i].legend(fontsize=9)
    axes[i].set_xlim(30, 105)

plt.tight_layout()
plt.show()

"""### Penjelasan Cell: Distribusi Index Kepuasan per Segmen Masyarakat

Cell ini memvisualisasikan distribusi `Index` kepuasan untuk setiap cluster menggunakan *histogram*. Visualisasi ini secara visual menegaskan perbedaan signifikan dalam tingkat kepuasan antar cluster, seperti yang juga divalidasi oleh uji Kruskal-Wallis, menunjukkan bagaimana masing-masing segmen memiliki rentang kepuasan yang berbeda.
"""

#===== Radar Chart Profil Cluster =====#


cluster_names = {0: 'Puas Merata', 1: 'Puas Tidak Merata', 2: 'Kurang Puas'}
cluster_colors = {0: '#2D6A4F', 1: '#F4A261', 2: '#E76F51'}

# Label pendek untuk radar
labels = ['Q1','Q2','Q3','Q4','Q5','Q6','Q7',
          'Q8','Q9','Q10','Q11','Q12','Q13','Q14','Q15']

N = len(labels)
angles = np.linspace(0, 2 * np.pi, N, endpoint=False).tolist()
angles += angles[:1]  # tutup lingkaran

fig, ax = plt.subplots(figsize=(9, 9), subplot_kw=dict(polar=True))

for cluster in [0, 1, 2]:
    values = cluster_profile.loc[cluster, q_cols].tolist()
    values += values[:1]  # tutup lingkaran

    ax.plot(angles, values, 'o-', linewidth=2,
            label=f"Cluster {cluster} — {cluster_names[cluster]}",
            color=cluster_colors[cluster])
    ax.fill(angles, values, alpha=0.1, color=cluster_colors[cluster])

ax.set_xticks(angles[:-1])
ax.set_xticklabels(labels, fontsize=11, fontweight='bold')
ax.set_ylim(50, 100)
ax.set_yticks([60, 70, 80, 90, 100])
ax.set_yticklabels(['60', '70', '80', '90', '100'], fontsize=8, color='gray')
ax.set_title('Radar Chart — Profil Rata-rata Jawaban per Cluster',
             fontsize=13, fontweight='bold', pad=20)
ax.legend(loc='upper right', bbox_to_anchor=(1.35, 1.15), fontsize=10)
ax.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.7)

plt.tight_layout()
plt.show()

"""### Penjelasan Cell: Radar Chart Profil Rata-rata Jawaban per Cluster

Cell ini memvisualisasikan profil rata-rata jawaban untuk setiap cluster menggunakan *radar chart*. Visualisasi ini sangat efektif untuk membandingkan secara visual "bentuk" atau "profil" setiap cluster, dengan cepat menunjukkan dimensi mana yang menjadi kekuatan atau kelemahan relatif untuk masing-masing segmen masyarakat.
"""

#===== Analisis per Dimensi =====#


# Pengelompokan dimensi
dimensi = {
    'Jangkauan & Akses'       : ['Q1', 'Q7', 'Q10', 'Q13'],
    'Kualitas Informasi'      : ['Q5', 'Q6', 'Q9', 'Q11'],
    'Retensi & Pemahaman'     : ['Q2', 'Q3', 'Q4'],
    'Kepercayaan & Identitas' : ['Q12'],
    'Utilitas & Dampak'       : ['Q8', 'Q14'],
    'Partisipasi Publik'      : ['Q15'],
}

# Hitung rata-rata skor per dimensi per cluster
rows = []
for dim_name, qs in dimensi.items():
    for cluster in [0, 1, 2]:
        sub = df[df['Cluster'] == cluster][qs].mean().mean()
        rows.append({
            'Dimensi' : dim_name,
            'Cluster' : cluster,
            'Skor'    : round(sub, 2)
        })

dim_df = pd.DataFrame(rows)
print(dim_df.pivot(index='Dimensi', columns='Cluster', values='Skor'))

"""### Penjelasan Cell: Analisis Rata-rata Skor per Dimensi

Cell ini mengelompokkan pertanyaan individu (Q1-Q15) ke dalam dimensi-dimensi yang lebih luas dan menghitung rata-rata skor untuk setiap dimensi per cluster. Hasilnya disajikan dalam bentuk *pivot table* (`dim_df`), yang memudahkan perbandingan performa setiap cluster pada level konseptual dimensi, bukan hanya pertanyaan individu.
"""

#===== Visualisasi Analisis per Dimensi =====#

cluster_names = {0: 'Puas Merata', 1: 'Puas Tidak Merata', 2: 'Kurang Puas'}
cluster_colors = {0: '#2D6A4F', 1: '#E09F3E', 2: '#C1440E'}

dim_names = list(dimensi.keys())
x = np.arange(len(dim_names))
width = 0.25

fig, ax = plt.subplots(figsize=(13, 6))

for i, cluster in enumerate([0, 1, 2]):
    vals = [dim_df[(dim_df['Dimensi'] == d) &
                   (dim_df['Cluster'] == cluster)]['Skor'].values[0]
            for d in dim_names]
    bars = ax.bar(x + i * width, vals, width,
                  label=f"Cluster {cluster} — {cluster_names[cluster]}",
                  color=cluster_colors[cluster], edgecolor='white', alpha=0.9)
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                f'{val:.1f}', ha='center', va='bottom', fontsize=7.5)

ax.set_title('Rata-rata Skor per Dimensi Pengelolaan Informasi Publik\nBerdasarkan Segmen Masyarakat',
             fontsize=13, fontweight='bold', pad=15)
ax.set_ylabel('Rata-rata Skor')
ax.set_xticks(x + width)
ax.set_xticklabels(dim_names, fontsize=9, rotation=15, ha='right')
ax.set_ylim(60, 100)
ax.legend(fontsize=9)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.axhline(75, color='gray', linestyle='--', linewidth=0.8, alpha=0.5)

plt.tight_layout()
plt.show()

"""### Penjelasan Cell: Gap Analysis per Dimensi

Cell ini menghitung 'Gap Score' dengan membandingkan rata-rata skor aktual setiap dimensi (gabungan seluruh responden) terhadap target ideal yang ditetapkan (85). Visualisasi ini membantu Diskominfo mengidentifikasi secara cepat dimensi mana yang paling jauh dari standar kualitas yang diinginkan.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Hitung skor rata-rata keseluruhan per dimensi (all respondents)
target_ideal = 85

dim_overall = []
for dim_name, qs in dimensi.items():
    avg_score = df[qs].mean().mean()
    dim_overall.append({
        'Dimensi': dim_name,
        'Skor': round(avg_score, 2),
        'Target': target_ideal,
        'Gap': round(avg_score - target_ideal, 2)
    })

gap_df = pd.DataFrame(dim_overall).sort_values('Gap')

# 2. Visualisasi
fig, ax = plt.subplots(figsize=(12, 7))

# Warna: Merah untuk gap negatif besar, Kuning/Hijau untuk yang mendekati target
colors = ['#E76F51' if x < -5 else '#F4A261' if x < -2 else '#52B788' for x in gap_df['Gap']]

bars = ax.barh(gap_df['Dimensi'], gap_df['Gap'], color=colors, edgecolor='white')

# Tambahkan garis vertikal di nol (target)
ax.axvline(0, color='black', linestyle='-', linewidth=1, alpha=0.5)

# Tambahkan label teks
for i, (gap, skor) in enumerate(zip(gap_df['Gap'], gap_df['Skor'])):
    label_pos = gap - 1.5 if gap < 0 else gap + 0.5
    ax.text(label_pos, i, f"Skor: {skor} (Gap: {gap})",
            va='center', fontsize=10, fontweight='bold',
            color='black' if gap > -3 else 'red')

ax.set_title(f'Gap Analysis: Performa Dimensi vs Target Ideal ({target_ideal})\nDiskominfo Provinsi Kalimantan Barat',
             fontsize=14, fontweight='bold', pad=20)
ax.set_xlabel('Selisih Skor (Gap)', fontsize=11)
ax.set_xlim(gap_df['Gap'].min() - 5, 5)

plt.grid(axis='x', linestyle='--', alpha=0.3)
plt.tight_layout()
plt.show()

# Tampilkan Tabel
display(gap_df[['Dimensi', 'Skor', 'Target', 'Gap']])

"""### Penjelasan Cell: Visualisasi Rata-rata Skor per Dimensi per Segmen Masyarakat

Cell ini memvisualisasikan rata-rata skor per dimensi untuk setiap segmen masyarakat menggunakan *grouped bar chart*. Visualisasi ini memberikan gambaran yang jelas tentang performa setiap cluster pada berbagai dimensi pengelolaan informasi publik, membantu dalam mengidentifikasi area yang perlu ditingkatkan untuk segmen tertentu.

### Ringkasan & Rekomendasi

Berikut adalah rangkuman dari hasil analisis segmentasi kepuasan masyarakat terhadap pengelolaan informasi publik Diskominfo Provinsi Kalimantan Barat:

---

#### **Kesimpulan Penelitian**

*   **Data**: 477 responden dari Survei Kepuasan Masyarakat (SKM) Diskominfo Kalbar 2023-2026.
*   **Metode**: K-Means Clustering + SHAP Explainability.

---

#### **Segmentasi Masyarakat (K=3 Cluster)**

*   **Cluster 0 · Puas Merata**: 200 responden (41.9%)
*   **Cluster 1 · Puas Tidak Merata**: 108 responden (22.6%)
*   **Cluster 2 · Kurang Puas**: 169 responden (35.4%)

---

#### **Top 5 Faktor Dominan (Berdasarkan SHAP Feature Importance Keseluruhan)**

1.  **Q10** - Kemudahan Akses Informasi (Nilai SHAP: 0.076)
2.  **Q6** - Kemudahan Memahami Informasi (Nilai SHAP: 0.055)
3.  **Q12** - Kemampuan Mengidentifikasi Informasi Resmi (Nilai SHAP: 0.049)
4.  **Q5** - Akurasi Informasi (Nilai SHAP: 0.045)
5.  **Q1** - Akses via Media Massa (Nilai SHAP: 0.044)

---

#### **Rekomendasi untuk Diskominfo Provinsi Kalimantan Barat**

1.  **Prioritaskan Kemudahan Akses**: Tingkatkan kemudahan akses ke platform informasi publik, terutama SIKEDIP (terkait **Q10**).
2.  **Perbaiki Keterbacaan & Kejelasan**: Pastikan konten informasi mudah dipahami oleh berbagai kalangan masyarakat (terkait **Q6**).
3.  **Perkuat Kredibilitas Informasi**: Edukasi masyarakat untuk membedakan informasi resmi dan hoaks, serta perkuat branding informasi resmi (terkait **Q12**).
4.  **Jaga Akurasi Data**: Perketat proses verifikasi dan validasi informasi sebelum dipublikasikan untuk menjaga akurasi (terkait **Q5**).
5.  **Optimalkan Jangkauan Media Massa**: Manfaatkan berbagai saluran media massa secara efektif untuk menyebarkan informasi (terkait **Q1**).

---

#### **Temuan Utama Tambahan**

*   **Demografi Bukan Penentu Utama**: Karakteristik demografi tidak secara signifikan membedakan tingkat kepuasan antar cluster; pola penilaian terhadap pertanyaanlah yang menjadi pembeda.
*   **Segmen 'Kurang Puas' Signifikan**: 35.4% masyarakat masih tergolong 'Kurang Puas', menunjukkan perlunya intervensi terarah.
*   **Akses Lebih Penting dari Konten**: Kemudahan akses informasi cenderung memiliki pengaruh yang lebih besar terhadap kepuasan dibandingkan dengan kualitas konten itu sendiri.
*   **Faktor Pendorong Kepuasan Berbeda**: Setiap cluster memiliki faktor-faktor dominan yang berbeda yang memengaruhi kepuasan mereka, menandakan perlunya pendekatan komunikasi dan pelayanan yang disesuaikan untuk setiap segmen.
"""